fragment imageHotspot on SanityImageHotspot {
  x
  y
  width
  height
}

fragment imageCrop on SanityImageCrop {
  top
  bottom
  left
  right
}

fragment seo on Seo {
  metaTitle
  metaDesc
  keywords
  shareGraphic {
    asset {
      url
      altText
    }
  }
}

fragment imageAsset on SanityImageAsset {
  url
  altText
}

query getLanding {
  allLanding {
    title
    landingImage {
      asset {
        ...imageAsset
      }
      hotspot {
        ...imageHotspot
      }
      crop {
        ...imageCrop
      }
    }
    seo {
      ...seo
    }
  }
}

query GetHome {
  allHome {
    heroImages {
      asset {
        ...imageAsset
      }
      hotspot {
        ...imageHotspot
      }
      crop {
        ...imageCrop
      }
    }
    heroHeadline
    copySubtitle
    copyTitleRaw
    copyRaw
    copyImage {
      asset {
        ...imageAsset
      }
      hotspot {
        ...imageHotspot
      }
      crop {
        ...imageCrop
      }
    }
    projectsSubtitle
    featuredProjects {
      title
      slug {
        current
      }
      heroImages {
        asset {
          ...imageAsset
        }
        hotspot {
          ...imageHotspot
        }
        crop {
          ...imageCrop
        }
      }
    }
    gallery {
      asset {
        ...imageAsset
      }
      hotspot {
        ...imageHotspot
      }
      crop {
        ...imageCrop
      }
    }
    slug {
      current
    }
    seo {
      ...seo
    }
  }
}

query GetAbout {
  allAbout {
    introSubtitle
    introTitleRaw
    introCopyRaw
    copySubtitle
    copyTitle
    copyRaw
    copyImage {
      asset {
        ...imageAsset
      }
      hotspot {
        ...imageHotspot
      }
      crop {
        ...imageCrop
      }
    }
    teamSubtitle
    teamTitle
    team {
      name
      email
      phone
      bioRaw
      image {
        asset {
          ...imageAsset
        }
        hotspot {
          ...imageHotspot
        }
        crop {
          ...imageCrop
        }
      }
    }
    slug {
      current
    }
    seo {
      ...seo
    }
  }
}

query GetContact {
  allContact {
    introSubtitle
    introTitleRaw
    introCopyRaw
    team {
      name
      email
      phone
      bioRaw
      image {
        asset {
          ...imageAsset
        }
        hotspot {
          ...imageHotspot
        }
        crop {
          ...imageCrop
        }
      }
    }
    slug {
      current
    }
    seo {
      ...seo
    }
  }
}

query GetProjectSingleton {
  page: allProjects {
    introSubtitle
    introTitleRaw
    introCopyRaw
    slug {
      current
    }
    seo {
      ...seo
    }
  }
  projects: allProject {
    heroImages {
      asset {
        ...imageAsset
      }
      crop {
        ...imageCrop
      }
      hotspot {
        ...imageHotspot
      }
    }
    heroHeadline
    slug {
      current
    }
    seo {
      ...seo
    }
  }
}

query GetProject($slug: String) {
  project: allProject(where: { slug: { current: { eq: $slug } } }) {
    heroImages {
      asset {
        ...imageAsset
      }
      crop {
        ...imageCrop
      }
      hotspot {
        ...imageHotspot
      }
    }
    heroHeadline
    projectSubtitle
    projectTitle
    projectCopyRaw
    gallery {
      asset {
        ...imageAsset
      }
      crop {
        ...imageCrop
      }
      hotspot {
        ...imageHotspot
      }
    }
    testimonialRaw
    testimonialAuthor
    slug {
      current
    }
    seo {
      ...seo
    }
  }
}
