fragment imageHotspot on SanityImageHotspot {
  x
  y
  width
  height
}

fragment imageCrop on SanityImageCrop {
  top
  bottom
  left
  right
}

fragment seo on Seo {
  metaTitle
  metaDesc
  keywords
  shareGraphic {
    asset {
      url
      altText
    }
  }
}

fragment imageAsset on SanityImageAsset {
  url
  altText
}

# query getLanding {
#   allLanding {
#     title
#     landingImage {
#       asset {
#         ...imageAsset
#       }
#       hotspot {
#         ...imageHotspot
#       }
#       crop {
#         ...imageCrop
#       }
#     }
#     seo {
#       ...seo
#     }
#   }
# }

fragment TextWithImageFragment on TextWithImage {
  reverseLayout
  applyBackground
  subtitle
  title
  titleLevel
  contentRaw
  links {
    label
    href
  }
  image {
    image {
      asset {
        ...imageAsset
        metadata {
          lqip
        }
      }
      hotspot {
        ...imageHotspot
      }
      crop {
        ...imageCrop
      }
    }
  }
}

fragment ContentBlockFragment on ContentBlocks {
  contentblocks {
    ... on TextWithImage {
      ...TextWithImageFragment
    }
  }
}

query GetHome {
  allHome {
    mobileHeroImages {
      asset {
        ...imageAsset
      }
      hotspot {
        ...imageHotspot
      }
      crop {
        ...imageCrop
      }
    }
    heroImages {
      asset {
        ...imageAsset
      }
      hotspot {
        ...imageHotspot
      }
      crop {
        ...imageCrop
      }
    }
    heroHeadline
    copySubtitle
    copyTitle
    copyRaw
    copyImage {
      asset {
        ...imageAsset
      }
      hotspot {
        ...imageHotspot
      }
      crop {
        ...imageCrop
      }
    }
    contentBlocks {
      ... on ContentBlocks {
        ...ContentBlockFragment
      }
    }
    projectsSubtitle
    featuredProjects {
      title
      slug {
        current
      }
      featuredProjectGallery {
        asset {
          ...imageAsset
        }
        hotspot {
          ...imageHotspot
        }
        crop {
          ...imageCrop
        }
      }
      gallery {
        asset {
          ...imageAsset
        }
        hotspot {
          ...imageHotspot
        }
        crop {
          ...imageCrop
        }
      }
    }
    gallery {
      asset {
        ...imageAsset
      }
      hotspot {
        ...imageHotspot
      }
      crop {
        ...imageCrop
      }
    }
    slug {
      current
    }
    seo {
      ...seo
    }
  }
  testimonials: allTestimonial {
    testimonial
    testimonialAuthor
  }
}

query GetAbout {
  allAbout {
    firstSubtitle
    firstTitle
    firstCopyRaw
    secondSubtitle
    secondTitle
    secondCopyRaw
    copyImage {
      asset {
        ...imageAsset
      }
      hotspot {
        ...imageHotspot
      }
      crop {
        ...imageCrop
      }
    }
    thirdSubtitle
    thirdTitle
    thirdCopyRaw
    thirdCopyImage {
      asset {
        ...imageAsset
      }
      hotspot {
        ...imageHotspot
      }
      crop {
        ...imageCrop
      }
    }
    slug {
      current
    }
    seo {
      ...seo
    }
    contentBlocks {
      ... on ContentBlocks {
        ...ContentBlockFragment
      }
    }
  }
}

query GetTeam {
  allTeam {
    teamSubtitle
    teamTitle
    team {
      name
      email
      phone
      bioRaw
      image {
        asset {
          ...imageAsset
        }
        hotspot {
          ...imageHotspot
        }
        crop {
          ...imageCrop
        }
      }
    }
    slug {
      current
    }
    seo {
      ...seo
    }
  }
}

query GetContact {
  allContact {
    introSubtitle
    introTitle
    introCopyRaw
    officePhoneNumber
    addressLine1
    addressLine2
    city
    postcode
    team {
      name
      email
      phone
      bioRaw
      image {
        asset {
          ...imageAsset
        }
        hotspot {
          ...imageHotspot
        }
        crop {
          ...imageCrop
        }
      }
    }
    gallery {
      asset {
        ...imageAsset
      }
      hotspot {
        ...imageHotspot
      }
      crop {
        ...imageCrop
      }
    }
    slug {
      current
    }
    seo {
      ...seo
    }
  }
}

query GetProjectSingleton {
  page: allProjects {
    introSubtitle
    introTitle
    introCopyRaw
    slug {
      current
    }
    contentBlocks {
      ... on ContentBlocks {
        ...ContentBlockFragment
      }
    }
    seo {
      ...seo
    }
  }
  projects: allProject(sort: [{ orderRank: ASC }]) {
    heroImages {
      asset {
        ...imageAsset
      }
      crop {
        ...imageCrop
      }
      hotspot {
        ...imageHotspot
      }
    }
    title
    projectLocation
    slug {
      current
    }
    seo {
      ...seo
    }
  }
}

query GetProject($slug: String) {
  project: allProject(where: { slug: { current: { eq: $slug } } }) {
    mobileHeroImages {
      asset {
        ...imageAsset
      }
      hotspot {
        ...imageHotspot
      }
      crop {
        ...imageCrop
      }
    }
    heroImages {
      asset {
        ...imageAsset
      }
      crop {
        ...imageCrop
      }
      hotspot {
        ...imageHotspot
      }
    }
    title
    projectCopyRaw
    projectCopyImage {
      asset {
        ...imageAsset
      }
      hotspot {
        ...imageHotspot
      }
      crop {
        ...imageCrop
      }
    }
    projectLocation
    projectValue
    projectInvolvement
    gallery {
      asset {
        ...imageAsset
      }
      crop {
        ...imageCrop
      }
      hotspot {
        ...imageHotspot
      }
    }
    slug {
      current
    }
    seo {
      ...seo
    }
    contentBlocks {
      ... on ContentBlocks {
        ...ContentBlockFragment
      }
    }
  }
}

fragment NavigationSection on NavigationSection {
  target {
    ... on Page {
      title
      slug {
        current
      }
    }
    ... on Home {
      title
      slug {
        current
      }
    }
    ... on About {
      title
      slug {
        current
      }
    }
    ... on Projects {
      title
      slug {
        current
      }
    }
    ... on Team {
      title
      slug {
        current
      }
    }
    ... on Page {
      title
      slug {
        current
      }
    }
  }
  children {
    title
    target {
      ... on Home {
        title
        slug {
          current
        }
      }
      ... on About {
        title
        slug {
          current
        }
      }
      ... on Projects {
        title
        slug {
          current
        }
      }
      ... on Team {
        title
        slug {
          current
        }
      }
      ... on Page {
        title
        slug {
          current
        }
      }
    }
  }
}

query GetNavigationById($id: ID!) {
  Navigation(id: $id) {
    _id
    title
    sections {
      ...NavigationSection
    }
  }
}

query GetPageBySlug($slug: String) {
  page: allPage(where: { slug: { current: { eq: $slug } } }) {
    _id
    title
    contentBlocks {
      ... on ContentBlocks {
        ...ContentBlockFragment
      }
    }
    seo {
      ...seo
    }
  }
}
